Blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from main import urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('main.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views

app_name = 'main'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^register/$', views.RegisterFormView.as_view(), name='register'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^login/$', views.LoginFormView.as_view(), name='login'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^new/$', views.Create_post.as_view(), name='create'),
    # Страница редактирования сигнатуры
    url(r'^update/(?P<pk>[0-9]+)/$', views.Update_post.as_view(), name='update'),
    # Страница удаления сигнатуры
    url(r'^delete/(?P<pk>[0-9]+)/$', views.Delete_post.as_view(), name='delete'),
]

main/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User

class Categories(models.Model):
    category = models.CharField('Категории', max_length=100)
    slug = models.SlugField(verbose_name='Транслит', null=True)


    class Meta():
        db_table = 'categories'
        ordering = ['category']
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.category


class Post(models.Model):
    author = models.ForeignKey(User, verbose_name='Автор', on_delete=models.CASCADE, default=User)
    title = models.CharField(verbose_name='Заголовок поста', max_length=100)
    image = models.ImageField(null=True, blank=True)
    post = models.TextField(verbose_name='Текст поста', blank=True)
    categories = models.ForeignKey(Categories, blank=True, verbose_name='Категория', on_delete=models.CASCADE)
    created_date = models.DateTimeField('Дата создания',
        default=timezone.now)


    class Meta():
        db_table = 'Post'
        ordering = ['title']
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'


    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('main:index')

main/forms.py
from django import forms

from .models import Post

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'image', 'post', 'categories')

main/views.py
from django.views import generic
from .models import Post, Categories
from django.views.generic.edit import UpdateView, DeleteView, CreateView, FormView
from django.views.generic.base import View
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login
from django.contrib.auth import logout
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy


class IndexView(generic.ListView):
    template_name = 'main/index.html'
    context_object_name = 'all_post'

    def get_queryset(self):
        return Post.objects.all()


class DetailView(generic.DetailView):
    model = Post
    template_name = 'main/detail.html'


class RegisterFormView(FormView):
    form_class = UserCreationForm
    success_url = "/login/"

    template_name = "main/register.html"

    def form_valid(self, form):
        form.save()
        return super(RegisterFormView, self).form_valid(form)


class LoginFormView(FormView):
    form_class = AuthenticationForm

    template_name = "main/login.html"
    success_url = "/"

    def form_valid(self, form):
        self.user = form.get_user()
        login(self.request, self.user)
        return super(LoginFormView, self).form_valid(form)


class LogoutView(View):
    def get(self, request):
        logout(request)
        return HttpResponseRedirect("/")


# Представление для создания сигнатуры
class Create_post(CreateView):
    model = Post
    fields = ['title', 'image', 'post', 'categories']


# Представление для изменения сигнатуры
class Update_post(UpdateView):
    model = Post
    fields = ['title', 'image', 'post', 'categories']


# Представление для удлаения сигнатуры
class Delete_post(DeleteView):
    model = Post
    success_url = reverse_lazy('main:index')

main/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Blog.me{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/style.css' %}">
    <script src="{% static 'main/js/jquery.min.js' %}"></script>
    <script src="{% static 'main/js/bootstrap.min.js' %}"></script>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand logo" href="{% url 'main:index' %}">
          Blog.me
      </a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#" class="">Home</a></li>
        <li><a href="https://github.com/MrJackJones">GitHub</a></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}
                    <li><a href="{% url 'main:create' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span> Добавить пост</a></li>
                    <li><a href="{% url 'main:logout' %}"  class="top-menu"><span class="glyphicon glyphicon-log-in"></span> Выход</a></li>
          {% else %}
                    <li><a href="{% url 'main:register' %}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
                    <li><a href="{% url 'main:login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
          {% endif %}


      </ul>
    </div>
  </div>
</nav>

<div class="container">
    <div class="row">
        <div class="col-md-3 menu">
        </div>
        <div class="col-md-9">
            {% block body %}
            {% endblock %}
        </div>
    </div>
</div>

</body>
</html>

main/templates/main/detail.html
{%  extends 'main/base.html' %}

{% block title %}{{ post }}{% endblock %}
{% block body %}

        <p><strong>{{ post.title }}</strong></p>
        <p><strong> Автор: </strong> {{ post.author }}</p>
        <p><strong> Дата создания: </strong> {{ post.created_date }}</p>
        <p>{{ post.post }}</p>
        <img src="{{ post.image.url }}" class="image_post img-responsive" />
    {% if user.is_authenticated and post.author == user %}
        <a href="{% url 'main:update' post.id %}" class="updateButton"><button class="button_update glyphicon glyphicon-edit"><span></span> Изменить</button></a>
        <form action="{% url 'main:delete' post.id %}" method="post">
        {% csrf_token %}
        <button class="button_delete glyphicon glyphicon-remove"><span> Удалить</span></button>
        </form>
    {% else %}
    {% endif %}
{% endblock %}

main/templates/main/index.html
{%  extends 'main/base.html' %}

{% block body %}

    {% for post in all_post %}
        <div class="row post">
        <p><strong><h3>{{ post.title }}</h3></strong></p>
            <p><strong> Автор: </strong> {{ post.author }}</p>
            <p><strong> Дата создания: </strong> {{ post.created_date }}</p>
        <p>{{ post.post|truncatewords:50 }}</p>
        <img src="{{ post.image.url }}" class="image_prew img-responsive" />

        <a href="{% url 'main:detail' post.id %}" ><button class="btn btn-default">Далее</button></a>
        {% for cat in category %}
            {{ cat.category }}
        {% endfor %}
        </div>
    {% endfor %}

{% endblock %}

main/templates/main/login.html
{%  extends 'main/base.html' %}

{% block body %}
    <form action="" method="post">
      {% csrf_token %}
      {{ form.as_p }}
        <script src='https://www.google.com/recaptcha/api.js'></script>
        <div class="g-recaptcha" data-sitekey="6LfMChcUAAAAAHCMuwf3tidPBi3JQy3A33rmouB4"></div>

         <button type="submit" class="btn btn-primary">Войти</button>

    </form>

{% endblock %}

main/templates/main/post_form.html
{% extends 'main/base.html' %}

{% block body %}
    {% if user.is_authenticated %}
    <h1>Добавить пост</h1>
    <form  class="form-horizontal"  method="POST" action="" enctype="multipart/form-data">
    <div  class="form-group col-sm-10">
            {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-default">Save</button>
    </div>
    </form>
    {% else %}
    {% endif %}
{% endblock %}

main/templates/main/register.html
{%  extends 'main/base.html' %}

{% block body %}
    <form action="" method="post">
      {% csrf_token %}
      {{ form.as_p }}
        <script src='https://www.google.com/recaptcha/api.js'></script>
        <div class="g-recaptcha" data-sitekey="6LfMChcUAAAAAHCMuwf3tidPBi3JQy3A33rmouB4"></div>

         <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
    </form>

{% endblock %}

main/templates/main/update_post.html
{% extends 'main/base.html' %}

{% block content %}
    {% if user.is_authenticated %}
    <h1>New Signature</h1>
    <form action="" method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update" />
    </form>
    {% else %}
    {% endif %}
{% endblock %}